### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by cseanburns** [bacon-GIT/ICT420_Webpages#1]
Some fixes:

- Remove all styling. Focus only on structure and content right now.
- The `align` attribute is deprecated. Remove that.
- Remove the `<b>` tags.
- The `<br>` tag should not be in the `<ol>` list
- The first descendant of any tag under `<ol>` should be an `<li>`. 

After fixing the above, try to validate at https://html5.validator.nu/

**Comment by bacon-GIT** [comment]
Fixed almost everything, will reformat the list in the future to solve the last issue raised
